onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /emu/cditop/scc68070_0/irq_ack
add wave -noupdate /emu/cditop/scc68070_0/autovector
add wave -noupdate /emu/cditop/scc68070_0/tg68/tg68kdotcinst/micro_state
add wave -noupdate /emu/cditop/scc68070_0/tg68/tg68kdotcinst/IPL
add wave -noupdate /emu/cditop/scc68070_0/tg68/tg68kdotcinst/IPL_autovector
add wave -noupdate /emu/cditop/scc68070_0/addr
add wave -noupdate /emu/cditop/scc68070_0/clk
add wave -noupdate /emu/cditop/scc68070_0/reset
add wave -noupdate -radix hexadecimal /emu/cditop/scc68070_0/internal_addr
add wave -noupdate /emu/cditop/scc68070_0/internal_data_in
add wave -noupdate /emu/cditop/scc68070_0/ipl
add wave -noupdate /emu/sdram/state
add wave -noupdate /emu/cditop/scc68070_0/tg68/addr_out
add wave -noupdate /emu/cditop/scc68070_0/tg68/berr
add wave -noupdate /emu/cditop/scc68070_0/tg68/busstate
add wave -noupdate /emu/cditop/scc68070_0/tg68/clk
add wave -noupdate /emu/cditop/scc68070_0/tg68/clkena_in
add wave -noupdate /emu/cditop/scc68070_0/tg68/data_in
add wave -noupdate /emu/cditop/scc68070_0/tg68/data_write
add wave -noupdate /emu/cditop/scc68070_0/tg68/FC
add wave -noupdate /emu/cditop/scc68070_0/tg68/IPL
add wave -noupdate /emu/cditop/scc68070_0/tg68/IPL_autovector
add wave -noupdate /emu/cditop/scc68070_0/tg68/nLDS
add wave -noupdate /emu/cditop/scc68070_0/tg68/nReset
add wave -noupdate /emu/cditop/scc68070_0/tg68/nResetOut
add wave -noupdate /emu/cditop/scc68070_0/tg68/nUDS
add wave -noupdate /emu/cditop/scc68070_0/tg68/nWr
add wave -noupdate /emu/cditop/scc68070_0/tg68/skipFetch
add wave -noupdate /emu/cditop/mcd212_inst/sdram_access
add wave -noupdate /emu/cditop/sdram_addr
add wave -noupdate /emu/cditop/sdram_busy
add wave -noupdate /emu/cditop/sdram_din
add wave -noupdate /emu/cditop/sdram_dout
add wave -noupdate /emu/cditop/sdram_rd
add wave -noupdate /emu/cditop/sdram_word
add wave -noupdate /emu/cditop/sdram_wr
add wave -noupdate /emu/sdram/a
add wave -noupdate /emu/sdram/ACCESS_TYPE
add wave -noupdate /emu/sdram/addr
add wave -noupdate /emu/sdram/BURST_LENGTH
add wave -noupdate /emu/sdram/busy
add wave -noupdate /emu/sdram/CAS_LATENCY
add wave -noupdate /emu/sdram/clk
add wave -noupdate /emu/sdram/CMD_ACTIVE
add wave -noupdate /emu/sdram/CMD_AUTO_REFRESH
add wave -noupdate /emu/sdram/CMD_BURST_TERMINATE
add wave -noupdate /emu/sdram/CMD_LOAD_MODE
add wave -noupdate /emu/sdram/CMD_NOP
add wave -noupdate /emu/sdram/CMD_PRECHARGE
add wave -noupdate /emu/sdram/CMD_READ
add wave -noupdate /emu/sdram/CMD_WRITE
add wave -noupdate /emu/sdram/data
add wave -noupdate /emu/sdram/din
add wave -noupdate /emu/sdram/dout
add wave -noupdate /emu/sdram/dqm
add wave -noupdate /emu/sdram/ds
add wave -noupdate /emu/sdram/init
add wave -noupdate /emu/sdram/init_old
add wave -noupdate /emu/sdram/last_data
add wave -noupdate /emu/sdram/MODE
add wave -noupdate /emu/sdram/mode
add wave -noupdate /emu/sdram/MODE_LDM
add wave -noupdate /emu/sdram/MODE_NORMAL
add wave -noupdate /emu/sdram/MODE_PRE
add wave -noupdate /emu/sdram/MODE_RESET
add wave -noupdate /emu/sdram/NO_WRITE_BURST
add wave -noupdate /emu/sdram/OP_MODE
add wave -noupdate /emu/sdram/ram_req
add wave -noupdate /emu/sdram/ram_req_test
add wave -noupdate /emu/sdram/RASCAS_DELAY
add wave -noupdate /emu/sdram/rd
add wave -noupdate /emu/sdram/reset
add wave -noupdate /emu/sdram/SDRAM_A
add wave -noupdate /emu/sdram/SDRAM_BA
add wave -noupdate /emu/sdram/SDRAM_CKE
add wave -noupdate /emu/sdram/SDRAM_CLK
add wave -noupdate /emu/sdram/SDRAM_DQ_in
add wave -noupdate /emu/sdram/SDRAM_DQ_out
add wave -noupdate /emu/sdram/SDRAM_DQMH
add wave -noupdate /emu/sdram/SDRAM_DQML
add wave -noupdate /emu/sdram/SDRAM_nCAS
add wave -noupdate /emu/sdram/SDRAM_nCS
add wave -noupdate /emu/sdram/SDRAM_nRAS
add wave -noupdate /emu/sdram/SDRAM_nWE
add wave -noupdate /emu/sdram/state
add wave -noupdate /emu/sdram/STATE_CONT
add wave -noupdate /emu/sdram/STATE_IDLE
add wave -noupdate /emu/sdram/STATE_LAST
add wave -noupdate /emu/sdram/STATE_READY
add wave -noupdate /emu/sdram/STATE_START
add wave -noupdate /emu/sdram/we
add wave -noupdate /emu/sdram/word
add wave -noupdate /emu/sdram/wr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {20928 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 264
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {3926 ps} {4057 ps}
